name: Django CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:9.4
        env:
          POSTGRES_DB: flight_booking
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.6.15

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install coverage
        pip install coveralls

    - name: Apply migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
      env: 
        DATABASE_URL: "postgres://postgres:5432/flight_booking"
        SECRET_KEY: "test_key"

    - name: Run tests
      run: |
        coverage run --source='.' ./manage.py test
        coverage report
      env: 
        DATABASE_URL: "postgres://postgres:postgres@postgres:5432/flight_booking"
        SECRET_KEY: "test_key"

    - name: Upload coverage to Coveralls
      run: coveralls


